In [1]:
import pandas as pd
data = r"C:\Users\Kaden\retail_sales_etl_pipeline\data\raw\data.csv"
data_ids = r"C:\Users\Kaden\retail_sales_etl_pipeline\data\raw\data_ids.csv"

data_df = pd.read_csv(data)
data_ids_df = pd.read_csv(data_ids)

print(data_df.head())
print("\nIDS")
print(data_ids_df.head())

                           Description  Quantity     InvoiceDate  UnitPrice  \
0   WHITE HANGING HEART T-LIGHT HOLDER         6  12/1/2010 8:26       2.55
1                  WHITE METAL LANTERN         6  12/1/2010 8:26       3.39
2       CREAM CUPID HEARTS COAT HANGER         8  12/1/2010 8:26       2.75
3  KNITTED UNION FLAG HOT WATER BOTTLE         6  12/1/2010 8:26       3.39
4       RED WOOLLY HOTTIE WHITE HEART.         6  12/1/2010 8:26       3.39

   CustomerID         Country
0     17850.0  United Kingdom
1     17850.0  United Kingdom
2     17850.0  United Kingdom
3     17850.0  United Kingdom
4     17850.0  United Kingdom

IDS
  InvoiceNo StockCode
0    536365    85123A
1    536365     71053
2    536365    84406B
3    536365    84029G
4    536365    84029E

Shape

In [2]:
print(data_df.shape)
print(data_ids_df.shape)

(541909, 6)
(541909, 2)

number of rows and columns

In [3]:
print(f"The number of rows in data_df are {len(data_df)}")
print(f"The number of columns in data_df are {len(data_df.columns)}")
print(f"data_df columns names are {data_df.columns.values}")

print(f"The number of rows in data_df are {len(data_ids_df)}")
print(f"The number of columns in data_ids_df are {len(data_ids_df.columns)}")
print(f"data_ids_df columns names are {data_ids_df.columns.values}")

The number of rows in data_df are 541909
The number of columns in data_df are 6
data_df columns names are ['Description' 'Quantity' 'InvoiceDate' 'UnitPrice' 'CustomerID' 'Country']
The number of rows in data_df are 541909
The number of columns in data_ids_df are 2
data_ids_df columns names are ['InvoiceNo' 'StockCode']

missing values

In [4]:
print(data_df.isna().sum())

print(data_ids_df.isna().sum())

Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64
InvoiceNo    0
StockCode    0
dtype: int64

duplicate rows

In [5]:
print(f"The number of duplcated rows are {data_df.duplicated().sum()}")
print(f"The number of duplcated rows are {data_ids_df.duplicated().sum()}")

true_dupes_in_data_df = data_df[data_df.duplicated(keep=False)].sort_values(by=['InvoiceDate','CustomerID'])
print(true_dupes_in_data_df.head())

true_dupes_in_data_ids_df = data_ids_df[data_ids_df.duplicated(keep=False)].sort_values(by=['InvoiceNo','StockCode'])
print(f"\n{true_dupes_in_data_ids_df.head()}")

The number of duplcated rows are 6007
The number of duplcated rows are 10684
                             Description  Quantity      InvoiceDate  \
51206     METAL SIGN,CUPCAKE SINGLE HOOK         2  1/10/2011 14:32
51207     METAL SIGN,CUPCAKE SINGLE HOOK         2  1/10/2011 14:32
51581  ANTIQUE SILVER TEA GLASS ENGRAVED         6  1/10/2011 14:57
51582  ANTIQUE SILVER TEA GLASS ENGRAVED         6  1/10/2011 14:57
51600               IVORY KITCHEN SCALES         1  1/10/2011 14:57

       UnitPrice  CustomerID         Country
51206       0.85         NaN  United Kingdom
51207       0.85         NaN  United Kingdom
51581       1.25     17406.0  United Kingdom
51582       1.25     17406.0  United Kingdom
51600       8.50     17406.0  United Kingdom

    InvoiceNo StockCode
113    536381     71270
125    536381     71270
494    536409     21866
517    536409     21866
485    536409     22111

data types

In [6]:
print(data_df.info())
print(data_ids_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Description  540455 non-null  object
 1   Quantity     541909 non-null  int64
 2   InvoiceDate  541909 non-null  object
 3   UnitPrice    541909 non-null  float64
 4   CustomerID   406829 non-null  float64
 5   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(3)
memory usage: 24.8+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 2 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   InvoiceNo  541909 non-null  object
 1   StockCode  541909 non-null  object
dtypes: object(2)
memory usage: 8.3+ MB
None

unique values

In [7]:
print(f"Number of unique values in Description: {data_df['Description'].nunique()}")
print(f"Number of unique values in Quantity: {data_df['Quantity'].nunique()}")
print(f"Number of unique values in InvoiceDate: {data_df['InvoiceDate'].nunique()}")
print(f"Number of unique values in UnitPrice: {data_df['UnitPrice'].nunique()}")
print(f"Number of unique values in CustomerID: {data_df['CustomerID'].nunique()}")
print(f"Number of unique values in Country: {data_df['Country'].nunique()}")

print("\ndata_ids_df\n")
print(f"Number of unique values in InvoiceNo: {data_ids_df['InvoiceNo'].nunique()}")
print(f"Number of unique values in StockCode: {data_ids_df['StockCode'].nunique()}")


print(data_df['Description'].unique())
print(data_df['Quantity'].unique())
print(data_df['InvoiceDate'].unique())
print(data_df['UnitPrice'].unique())
print(data_df['CustomerID'].unique())
print(data_df['Country'].unique())


print(data_ids_df['InvoiceNo'].unique())
print(data_ids_df['StockCode'].unique())

Number of unique values in Description: 4223
Number of unique values in Quantity: 722
Number of unique values in InvoiceDate: 23260
Number of unique values in UnitPrice: 1630
Number of unique values in CustomerID: 4372
Number of unique values in Country: 38

data_ids_df

Number of unique values in InvoiceNo: 25900
Number of unique values in StockCode: 4070
['WHITE HANGING HEART T-LIGHT HOLDER' 'WHITE METAL LANTERN'
 'CREAM CUPID HEARTS COAT HANGER' ... 'lost'
 'CREAM HANGING HEART T-LIGHT HOLDER' 'PAPER CRAFT , LITTLE BIRDIE']
[     6      8      2     32      3      4     24     12     48     18
     20     36     80     64     10    120     96     23      5      1
     -1     50     40    100    192    432    144    288    -12    -24
     16      9    128     25     30     28      7     56     72    200
    600    480     -6     14     -2     11     33     13     -4     -5
     -7     -3     70    252     60    216    384    -10     27     15
     22     19     17     21     34     47    108     52  -9360    -38
     75    270     42    240     90    320   1824    204     69    -36
   -192   -144    160   2880   1400     39    -48    -50     26   1440
     31     82     78     97     98     35     57    -20    110    -22
    -30    -70   -130    -80   -120    -40    -25    -14    -15    -69
   -140   -320     -8    720    156    324     38     37     49     95
     -9    -11     29     41    -72    -35    -21    -43    -19    -18
    -44    402    378    150    300     54    104     67    258     66
     44     55     46     99     61    408    972    208   1008   1000
    -77   1488    250   1394    400   -223   -150    -13    -33   -723
   -177     79     84    -32   -100    -28    272   -145    -47    -96
    113     45    106     68    267    115     65   1728    -60    -16
     53   -240     76    460     71     43    213     58    576   2400
    500    180   -300   -500    -23    752    960   1296    210    172
    215    129    138    116    135    197   -106    -54    -17   -939
    147    168    256   -201    -53    -29  -2600   -990   -290    -45
    860   1010   1356   1284    186    114    360   1930   2000   3114
   1300    670    111    211     59   -310    -61    -41    176    648
     62  74215 -74215    -64    -84     89  -1400     73    -57    112
    456    -59    -31   5568   2560    136    900   -600    -42    -94
   -207    -52    130   -206   2592    420    800    101   1200    864
   -217     94  -1430   1287   -162   -230   -173   -390   -234    504
    123    118    -76   -200   1056   1500    280    407    141    124
    -99     51    -92   -741   3906   -400   -114    102   1152    -88
    198    117     86   -720    125    -86   -391    -87   -278    140
    228   -154  -3000     81   -675   -210   -345   -975  -1200  -1121
    -27   -541  -1277   -197   3000  -1100    -63  -5368    219   -259
    232    -82   -178    170   -110    768     88    700   -102   2160
   -323   -450   -232    -83   -153   -524  -2472    -49   -105    342
    304    167    -34    640    175    220     74     93    164    163
     63    637    122    158    165    350    -46    -75   -690    -39
    -66     83    312   -180    392   -624   -194    -26    -62    -37
    -91   -139   -158  -1479    -55   -576   -750    330    151    -93
   -432    -58  -1092   -670  -1300  -1930  -2000  -3114    462    -65
    -68    492   -620    273    -90   -170  -1512    -51     85    -56
   -160   -360    105   -960  -2376   1350    428  -1350    336   -786
   -590   -168   -101    -71    132   -413   -664    227   2700    222
    246    906    756    888    552    -97    224    738    608   -212
   4300    146    143    276   -125   -116   -108   4000   -304   -272
  -1206    -95   1600    323   -161   -472   -618   -204   1515  -1515
  -9058  -9600    660   -420   -126   -220   -271  -1440    264    188
    588    612    152   -324   -480   -164    -78   -118    430  -1681
     87    155    701    828    540    696    560   -250   -408   -179
    121   -124    512   -251  -3100   3100   -169    126    291   3186
  -2834   -109    109   -121   -530   -227    261   -346    352    142
    107   -188  -1060   -342   -288    348   1900    157   -343   -455
    425    968    684    824   -828   -701    196    248    410    236
    230   -156   -553    145    448    245   -252   -334   -318   -113
   -115    171   -242    840   -967   -203  -3167   -443  -1897    225
   -434    750   -682   -484    682    344   -635   -117  -3667    450
    310    494   -384     92   1788   -138    624    744    416    496
    396    306   1878   1944    666    708   1428    852   1412    528
   -756   -752   -152    -85   -312    -79   -147    -67   -131    183
   -209   -186   -231   -129   -458   -275  -2880   1540    672   -800
   -430   -380    -74   -840  -1296   -365   -104   -270    -73   -306
     91    255    468   -468   -111   -184   -103   -335   4800   -112
  -1000    912   1992    184    148   -657  -1671  -1158  -2618  -2003
   -674  -4830   -905  -1128    832    992    630   1020   2100    162
  -1560  -1284    -81    314    370    131    133    484    149    153
    257    139    137    628    179   1820    478    335    253    242
    375   -276   -256    281    193    181    404    244    207    199
   1130    326    654    688    268    249   -864    234  -1510   -550
   -244   -132   -327   -313    279   -398   -280    374   -504   -696
   -149   -224   -428    212   -267   -175  12540    760    -98    774
   -151   2040  -1131   -135   1120     77   -900    177    490    388
    620   1404   -155   -355   -337  -1050   -338    205   -235    698
  80995 -80995]
['12/1/2010 8:26' '12/1/2010 8:28' '12/1/2010 8:34' ... '12/9/2011 12:31'
 '12/9/2011 12:49' '12/9/2011 12:50']
[   2.55    3.39    2.75 ...  933.17 1714.17  224.69]
[17850. 13047. 12583. ... 13298. 14569. 12713.]
['United Kingdom' 'France' 'Australia' 'Netherlands' 'Germany' 'Norway'
 'EIRE' 'Switzerland' 'Spain' 'Poland' 'Portugal' 'Italy' 'Belgium'
 'Lithuania' 'Japan' 'Iceland' 'Channel Islands' 'Denmark' 'Cyprus'
 'Sweden' 'Austria' 'Israel' 'Finland' 'Bahrain' 'Greece' 'Hong Kong'
 'Singapore' 'Lebanon' 'United Arab Emirates' 'Saudi Arabia'
 'Czech Republic' 'Canada' 'Unspecified' 'Brazil' 'USA'
 'European Community' 'Malta' 'RSA']
['536365' '536366' '536367' ... '581585' '581586' '581587']
['85123A' '71053' '84406B' ... '90214U' '47591b' '23843']

In [8]:
data_df.head()

,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [9]:
data_ids_df.head()

  InvoiceNo StockCode
0    536365    85123A
1    536365     71053
2    536365    84406B
3    536365    84029G
4    536365    84029E

In [10]:
raw_transactions = pd.concat([data_ids_df,data_df], axis=1)

print(raw_transactions.head())

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

      InvoiceDate  UnitPrice  CustomerID         Country
0  12/1/2010 8:26       2.55     17850.0  United Kingdom
1  12/1/2010 8:26       3.39     17850.0  United Kingdom
2  12/1/2010 8:26       2.75     17850.0  United Kingdom
3  12/1/2010 8:26       3.39     17850.0  United Kingdom
4  12/1/2010 8:26       3.39     17850.0  United Kingdom

In [11]:
print(f"The number of row in raw_transaction is {len(raw_transactions)}")
print(f"The number of columns in raw_transaction is {len(raw_transactions.columns)}")
print(raw_transactions.info())
print("\nThe missing values of raw_transaction")
print(raw_transactions.isna().sum())

The number of row in raw_transaction is 541909
The number of columns in raw_transaction is 8
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB
None

The missing values of raw_transaction
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [12]:
invoiceno_start_with_c = raw_transactions[raw_transactions['InvoiceNo'].str.startswith('C', na=False)]
print(invoiceno_start_with_c.head())

print((invoiceno_start_with_c['Quantity'] < 0).all())

    InvoiceNo StockCode                       Description  Quantity  \
141   C536379         D                          Discount        -1
154   C536383    35004C   SET OF 3 COLOURED  FLYING DUCKS        -1
235   C536391     22556    PLASTERS IN TIN CIRCUS PARADE        -12
236   C536391     21984  PACK OF 12 PINK PAISLEY TISSUES        -24
237   C536391     21983  PACK OF 12 BLUE PAISLEY TISSUES        -24

         InvoiceDate  UnitPrice  CustomerID         Country
141   12/1/2010 9:41      27.50     14527.0  United Kingdom
154   12/1/2010 9:49       4.65     15311.0  United Kingdom
235  12/1/2010 10:24       1.65     17548.0  United Kingdom
236  12/1/2010 10:24       0.29     17548.0  United Kingdom
237  12/1/2010 10:24       0.29     17548.0  United Kingdom
True

In [13]:
non_c_invoices = raw_transactions[~raw_transactions['InvoiceNo'].str.startswith('C', na=False)]

print("Any negative quantities in regular invoices:", (non_c_invoices['Quantity'] < 0).any())

Any negative quantities in regular invoices: True

In [14]:
hidden_negatives = raw_transactions[
    (~raw_transactions['InvoiceNo'].str.startswith('C', na=False)) & 
    (raw_transactions['Quantity'] < 0)
]


print(f"Total hidden negative rows: {len(hidden_negatives)}")
print(hidden_negatives.head())

Total hidden negative rows: 1336
     InvoiceNo StockCode Description  Quantity      InvoiceDate  UnitPrice  \
2406    536589     21777         NaN       -10  12/1/2010 16:50        0.0
4347    536764    84952C         NaN       -38  12/2/2010 14:42        0.0
7188    536996     22712         NaN       -20  12/3/2010 15:30        0.0
7189    536997     22028         NaN       -20  12/3/2010 15:30        0.0
7190    536998     85067         NaN        -6  12/3/2010 15:30        0.0

      CustomerID         Country
2406         NaN  United Kingdom
4347         NaN  United Kingdom
7188         NaN  United Kingdom
7189         NaN  United Kingdom
7190         NaN  United Kingdom

In [15]:
missing_ID_desc_price = hidden_negatives[
    (hidden_negatives['CustomerID'].isna()) &
    (hidden_negatives['Description'].isna()) &
    (hidden_negatives['UnitPrice'] == 0)                              
                                         ]

print(f"Total number of rows that have missing customerID, description and unitprice is 0: {len(missing_ID_desc_price)}")

Total number of rows that have missing customerID, description and unitprice is 0: 862

In [16]:
print((missing_ID_desc_price['UnitPrice'] != 0).sum())
print((missing_ID_desc_price['CustomerID'].notna()).sum())
print((missing_ID_desc_price['Description'].notna()).sum())

0
0
0

In [17]:
remaining_hidden_negatives = hidden_negatives[~hidden_negatives.index.isin(missing_ID_desc_price.index)]

print(remaining_hidden_negatives.head())

print(len(remaining_hidden_negatives))

      InvoiceNo StockCode Description  Quantity      InvoiceDate  UnitPrice  \
7313     537032     21275           ?       -30  12/3/2010 16:50        0.0
13217    537425    84968F       check       -20  12/6/2010 15:35        0.0
13218    537426    84968E       check       -35  12/6/2010 15:36        0.0
13264    537432    35833G     damages       -43  12/6/2010 16:10        0.0
21338    538072     22423      faulty       -13  12/9/2010 14:10        0.0

       CustomerID         Country
7313          NaN  United Kingdom
13217         NaN  United Kingdom
13218         NaN  United Kingdom
13264         NaN  United Kingdom
21338         NaN  United Kingdom
474

In [18]:
print((remaining_hidden_negatives['UnitPrice'] == 0).sum())
print((remaining_hidden_negatives['CustomerID'].isna()).sum())
unique_list = remaining_hidden_negatives['Description'].unique().tolist()
print(unique_list)
print(remaining_hidden_negatives['Description'].nunique())

474
474
['?', 'check', 'damages', 'faulty', 'Dotcom sales', 'reverse 21/5/10 adjustment', 'mouldy, thrown away.', 'counted', 'Given away', 'Dotcom', 'label mix up', 'samples/damages', 'thrown away', 'incorrectly made-thrown away.', 'showroom', 'MIA', 'Dotcom set', 'wrongly sold as sets', 'Amazon sold sets', 'dotcom sold sets', 'wrongly sold sets', '? sold as sets?', '?sold as sets?', 'Thrown away.', 'damages/display', 'damaged stock', 'broken', 'throw away', 'wrong barcode (22467)', 'wrong barcode', 'barcode problem', '?lost', "thrown away-can't sell.", "thrown away-can't sell", 'damages?', 're dotcom quick fix.', "Dotcom sold in 6's", 'sold in set?', 'cracked', 'sold as 22467', 'Damaged', 'mystery! Only ever imported 1800', 'MERCHANT CHANDLER CREDIT ERROR, STO', 'POSSIBLE DAMAGES OR LOST?', 'damaged', 'DAMAGED', 'Display', 'Missing', 'wrong code?', 'wrong code', 'adjust', 'crushed', 'damages/showroom etc', 'samples', 'damages/credits from ASOS.', 'Not rcvd in 10/11/2010 delivery', 'Thrown away-rusty', 'sold as set/6 by dotcom', 'wet/rusty', 'damages/dotcom?', 'smashed', 'reverse previous adjustment', 'incorrectly credited C550456 see 47', 'wet damaged', 'Water damaged', 'missing', 'sold as set on dotcom', 'sold as set on dotcom and amazon', 'water damage', 'sold as set by dotcom', 'Printing smudges/thrown away', 'printing smudges/thrown away', 'found some more on shelf', 'Show Samples', 'mix up with c', 'mouldy, unsaleable.', 'wrongly marked. 23343 in box', 'stock creditted wrongly', 'ebay', 'incorrectly put back into stock', 'Damages/samples', 'Sold as 1 on dotcom', 'taig adjust no stock', 'code mix up? 84930', '?display?', 'sold as 1', '?missing', 'crushed ctn', 'Crushed', 'temp adjustment', '??', 'test', 'OOPS ! adjustment', 'Dagamed', 'historic computer difference?....se', 'Incorrect stock entry.', 'incorrect stock entry.', 'wrongly coded-23343', 'stock check', 'crushed boxes', 'WET/MOULDY', "can't find", 'mouldy', 'Wet pallet-thrown away', 'adjustment', '20713 wrongly marked', 're-adjustment', 'Breakages', '20713', 'wrongly coded 20713', 'Damages', 'CHECK', 'Unsaleable, destroyed.', 'dotcom sales', 'damages wax', 'water damaged', 'Wrongly mrked had 85123a in box', 'wrongly marked carton 22804', 'missing?', 'wet rusty', '???lost', 'sold with wrong barcode', 'rusty thrown away', 'rusty throw away', 'dotcom', '?? missing', 'wet pallet', '????missing', '???missing', 'lost in space', 'wet?', 'lost??', '???', 'wet', 'wet boxes', '????damages????', 'mixed up', 'lost']
138

In [19]:
cancellation_row_no_custID_desc_unit = raw_transactions[
    (raw_transactions['InvoiceNo'].str.startswith('C', na=False)) &
    (raw_transactions['CustomerID'].isna()) &
    (raw_transactions['Description'].isna()) &
    (raw_transactions['UnitPrice'] == 0)]

print(len(cancellation_row_no_custID_desc_unit))

print(len(raw_transactions[(raw_transactions['InvoiceNo'].str.startswith('C', na=False)) &
    (raw_transactions['CustomerID'].isna())]))

print(len(raw_transactions[(raw_transactions['InvoiceNo'].str.startswith('C', na=False)) & (raw_transactions['Description'].isna())]))

print(len(raw_transactions[(raw_transactions['InvoiceNo'].str.startswith('C', na=False)) & (raw_transactions['UnitPrice'] == 0)]))

0
383
0
0

In [20]:
print(raw_transactions.duplicated().sum())

print()

5268

In [21]:
duplicated_raw_transactions = raw_transactions[raw_transactions.duplicated(keep=False)]
duplicated_raw_transactions = duplicated_raw_transactions.sort_values(by=list(raw_transactions.columns))

duplicated_raw_transactions.head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
494,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,12/1/2010 11:45,1.25,17908.0,United Kingdom
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,12/1/2010 11:45,1.25,17908.0,United Kingdom
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,12/1/2010 11:45,4.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,12/1/2010 11:45,4.95,17908.0,United Kingdom
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,12/1/2010 11:45,2.10,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,12/1/2010 11:45,2.10,17908.0,United Kingdom
521,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,12/1/2010 11:45,2.95,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,12/1/2010 11:45,2.95,17908.0,United Kingdom
578,536412,21448,12 DAISY PEGS IN WOOD BOX,1,12/1/2010 11:49,1.65,17920.0,United Kingdom
598,536412,21448,12 DAISY PEGS IN WOOD BOX,1,12/1/2010 11:49,1.65,17920.0,United Kingdom
565,536412,21448,12 DAISY PEGS IN WOOD BOX,2,12/1/2010 11:49,1.65,17920.0,United Kingdom
601,536412,21448,12 DAISY PEGS IN WOOD BOX,2,12/1/2010 11:49,1.65,17920.0,United Kingdom
604,536412,21448,12 DAISY PEGS IN WOOD BOX,2,12/1/2010 11:49,1.65,17920.0,United Kingdom
612,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,12/1/2010 11:49,4.95,17920.0,United Kingdom
618,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,12/1/2010 11:49,4.95,17920.0,United Kingdom
607,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,12/1/2010 11:49,4.95,17920.0,United Kingdom
616,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,12/1/2010 11:49,4.95,17920.0,United Kingdom
574,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,12/1/2010 11:49,2.10,17920.0,United Kingdom
594,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,12/1/2010 11:49,2.10,17920.0,United Kingdom
556,536412,22273,FELTCRAFT DOLL MOLLY,1,12/1/2010 11:49,2.95,17920.0,United Kingdom

In [22]:
raw_transactions['InvoiceDate'] = pd.to_datetime(raw_transactions["InvoiceDate"], errors='coerce')

print(raw_transactions['InvoiceDate'])

max_transaction_date = raw_transactions['InvoiceDate'].max()
min_transaction_date = raw_transactions['InvoiceDate'].min()

print(raw_transactions['InvoiceDate'].isna().sum())
print(f"The transaction date range is from {min_transaction_date} to {max_transaction_date}")

0        2010-12-01 08:26:00
1        2010-12-01 08:26:00
2        2010-12-01 08:26:00
3        2010-12-01 08:26:00
4        2010-12-01 08:26:00
                 ...
541904   2011-12-09 12:50:00
541905   2011-12-09 12:50:00
541906   2011-12-09 12:50:00
541907   2011-12-09 12:50:00
541908   2011-12-09 12:50:00
Name: InvoiceDate, Length: 541909, dtype: datetime64[ns]
0
The transaction date range is from 2010-12-01 08:26:00 to 2011-12-09 12:50:00

In [23]:
unit_price_less_zero = raw_transactions[raw_transactions['UnitPrice'] < 0]
print(unit_price_less_zero)
print(len(unit_price_less_zero))

       InvoiceNo StockCode      Description  Quantity         InvoiceDate  \
299983   A563186         B  Adjust bad debt         1 2011-08-12 14:51:00
299984   A563187         B  Adjust bad debt         1 2011-08-12 14:52:00

        UnitPrice  CustomerID         Country
299983  -11062.06         NaN  United Kingdom
299984  -11062.06         NaN  United Kingdom
2

In [24]:
no_cust_id_positive_quanitity = raw_transactions[
    (raw_transactions['CustomerID'].isna()) &
    (raw_transactions['Quantity'] > 0)
    ]

print(no_cust_id_positive_quanitity)
print(len(no_cust_id_positive_quanitity))

       InvoiceNo StockCode                      Description  Quantity  \
622       536414     22139                              NaN        56
1443      536544     21773  DECORATIVE ROSE BATHROOM BOTTLE         1
1444      536544     21774  DECORATIVE CATS BATHROOM BOTTLE         2
1445      536544     21786               POLKADOT RAIN HAT          4
1446      536544     21787            RAIN PONCHO RETROSPOT         2
...          ...       ...                              ...       ...
541536    581498    85099B          JUMBO BAG RED RETROSPOT         5
541537    581498    85099C   JUMBO  BAG BAROQUE BLACK WHITE         4
541538    581498     85150    LADIES & GENTLEMEN METAL SIGN         1
541539    581498     85174                S/4 CACTI CANDLES         1
541540    581498       DOT                   DOTCOM POSTAGE         1

               InvoiceDate  UnitPrice  CustomerID         Country
622    2010-12-01 11:52:00       0.00         NaN  United Kingdom
1443   2010-12-01 14:32:00       2.51         NaN  United Kingdom
1444   2010-12-01 14:32:00       2.51         NaN  United Kingdom
1445   2010-12-01 14:32:00       0.85         NaN  United Kingdom
1446   2010-12-01 14:32:00       1.66         NaN  United Kingdom
...                    ...        ...         ...             ...
541536 2011-12-09 10:26:00       4.13         NaN  United Kingdom
541537 2011-12-09 10:26:00       4.13         NaN  United Kingdom
541538 2011-12-09 10:26:00       4.96         NaN  United Kingdom
541539 2011-12-09 10:26:00      10.79         NaN  United Kingdom
541540 2011-12-09 10:26:00    1714.17         NaN  United Kingdom

[133361 rows x 8 columns]
133361

In [25]:
no_cust_id_cancellations = raw_transactions[
    (raw_transactions['CustomerID'].isna()) &
    (raw_transactions['InvoiceNo'].str.startswith('C', na=False)) & 
    (raw_transactions['Quantity'] < 0)
    ]

print(no_cust_id_cancellations)
print(len(no_cust_id_cancellations))

       InvoiceNo  StockCode                         Description  Quantity  \
11502    C537251      22429          ENAMEL MEASURING JUG CREAM        -2
11503    C537251      22620         4 TRADITIONAL SPINNING TOPS        -8
11504    C537251      21890   S/6 WOODEN SKITTLES IN COTTON BAG        -2
11505    C537251      22564              ALPHABET STENCIL CRAFT        -5
11506    C537251      21891    TRADITIONAL WOODEN SKIPPING ROPE        -3
...          ...        ...                                 ...       ...
492207   C578097      22112          CHOCOLATE HOT WATER BOTTLE       -48
514984   C579757      47469  ASSORTED SHAPES PHOTO CLIP SILVER        -24
516454   C579907      22169    FAMILY ALBUM WHITE PICTURE FRAME        -2
524601   C580604  AMAZONFEE                          AMAZON FEE        -1
524602   C580605  AMAZONFEE                          AMAZON FEE        -1

               InvoiceDate  UnitPrice  CustomerID         Country
11502  2010-12-06 10:45:00       4.25         NaN  United Kingdom
11503  2010-12-06 10:45:00       1.25         NaN  United Kingdom
11504  2010-12-06 10:45:00       2.95         NaN  United Kingdom
11505  2010-12-06 10:45:00       1.25         NaN  United Kingdom
11506  2010-12-06 10:45:00       1.25         NaN  United Kingdom
...                    ...        ...         ...             ...
492207 2011-11-22 17:31:00       4.25         NaN  United Kingdom
514984 2011-11-30 14:56:00       0.65         NaN  United Kingdom
516454 2011-12-01 08:48:00       7.65         NaN            EIRE
524601 2011-12-05 11:35:00   11586.50         NaN  United Kingdom
524602 2011-12-05 11:36:00   17836.46         NaN  United Kingdom

[383 rows x 8 columns]
383

In [26]:
no_cust_id_inventory_adjust = raw_transactions[
    (raw_transactions['CustomerID'].isna()) &
    (raw_transactions['UnitPrice'] == 0) &
    (raw_transactions['Quantity'] < 0)
    ]

print(no_cust_id_inventory_adjust)
print(len(no_cust_id_inventory_adjust))

       InvoiceNo StockCode Description  Quantity         InvoiceDate  \
2406      536589     21777         NaN       -10 2010-12-01 16:50:00
4347      536764    84952C         NaN       -38 2010-12-02 14:42:00
7188      536996     22712         NaN       -20 2010-12-03 15:30:00
7189      536997     22028         NaN       -20 2010-12-03 15:30:00
7190      536998     85067         NaN        -6 2010-12-03 15:30:00
...          ...       ...         ...       ...                 ...
535333    581210     23395       check       -26 2011-12-07 18:36:00
535335    581212     22578        lost     -1050 2011-12-07 18:38:00
535336    581213     22576       check       -30 2011-12-07 18:38:00
536908    581226     23090     missing      -338 2011-12-08 09:56:00
538919    581422     23169     smashed      -235 2011-12-08 15:24:00

        UnitPrice  CustomerID         Country
2406          0.0         NaN  United Kingdom
4347          0.0         NaN  United Kingdom
7188          0.0         NaN  United Kingdom
7189          0.0         NaN  United Kingdom
7190          0.0         NaN  United Kingdom
...           ...         ...             ...
535333        0.0         NaN  United Kingdom
535335        0.0         NaN  United Kingdom
535336        0.0         NaN  United Kingdom
536908        0.0         NaN  United Kingdom
538919        0.0         NaN  United Kingdom

[1336 rows x 8 columns]
1336

In [27]:
no_cust_id_account_adjust = raw_transactions[
    (raw_transactions['CustomerID'].isna()) &
    (raw_transactions['UnitPrice'] < 0)
    ]

print(no_cust_id_account_adjust)
print(len(no_cust_id_account_adjust))

       InvoiceNo StockCode      Description  Quantity         InvoiceDate  \
299983   A563186         B  Adjust bad debt         1 2011-08-12 14:51:00
299984   A563187         B  Adjust bad debt         1 2011-08-12 14:52:00

        UnitPrice  CustomerID         Country
299983  -11062.06         NaN  United Kingdom
299984  -11062.06         NaN  United Kingdom
2

In [28]:
positive_quantity_unit_zero = raw_transactions[
    (raw_transactions['Quantity'] > 0) &
    (raw_transactions['UnitPrice'] == 0)
    ]

print(positive_quantity_unit_zero)
print(len(positive_quantity_unit_zero))

print(positive_quantity_unit_zero['Description'].value_counts(dropna=False).head(30))

       InvoiceNo StockCode                   Description  Quantity  \
622       536414     22139                           NaN        56
1970      536545     21134                           NaN         1
1971      536546     22145                           NaN         1
1972      536547     37509                           NaN         1
1987      536549    85226A                           NaN         1
...          ...       ...                           ...       ...
535334    581211     22142                         check        14
536981    581234     72817                           NaN        27
538504    581406    46000M  POLYESTER FILLER PAD 45x45cm       240
538505    581406    46000S  POLYESTER FILLER PAD 40x40cm       300
538554    581408     85175                           NaN        20

               InvoiceDate  UnitPrice  CustomerID         Country
622    2010-12-01 11:52:00        0.0         NaN  United Kingdom
1970   2010-12-01 14:32:00        0.0         NaN  United Kingdom
1971   2010-12-01 14:33:00        0.0         NaN  United Kingdom
1972   2010-12-01 14:33:00        0.0         NaN  United Kingdom
1987   2010-12-01 14:34:00        0.0         NaN  United Kingdom
...                    ...        ...         ...             ...
535334 2011-12-07 18:36:00        0.0         NaN  United Kingdom
536981 2011-12-08 10:33:00        0.0         NaN  United Kingdom
538504 2011-12-08 13:58:00        0.0         NaN  United Kingdom
538505 2011-12-08 13:58:00        0.0         NaN  United Kingdom
538554 2011-12-08 14:06:00        0.0         NaN  United Kingdom

[1179 rows x 8 columns]
1179
Description
NaN                                  592
check                                 39
found                                 25
adjustment                            14
FRENCH BLUE METAL DOOR SIGN 1          9
FRENCH BLUE METAL DOOR SIGN 8          8
amazon                                 8
Found                                  8
FRENCH BLUE METAL DOOR SIGN 3          7
RECIPE BOX PANTRY YELLOW DESIGN        7
OWL DOORSTOP                           7
FRENCH BLUE METAL DOOR SIGN 4          7
Amazon                                 7
FRENCH BLUE METAL DOOR SIGN No         7
RED KITCHEN SCALES                     6
?                                      6
MINT KITCHEN SCALES                    6
FRENCH BLUE METAL DOOR SIGN 9          6
FRENCH BLUE METAL DOOR SIGN 7          6
Manual                                 6
FRENCH BLUE METAL DOOR SIGN 6          6
FRENCH BLUE METAL DOOR SIGN 5          6
RED RETROSPOT CHARLOTTE BAG            5
FRENCH BLUE METAL DOOR SIGN 2          5
RECIPE BOX BLUE SKETCHBOOK DESIGN      5
POLYESTER FILLER PAD 45x45cm           5
ENAMEL WATERING CAN CREAM              5
BOX OF 24 COCKTAIL PARASOLS            5
IVORY KITCHEN SCALES                   5
CHILDS GARDEN SPADE BLUE               5
Name: count, dtype: int64

In [29]:
import numpy as np


# account adjustment
    # unitprice < 0 
# cancellation
    # InvoiceNo starts with "C"
# inventory adjustment 
    # quantity < 0 
    # unitprice == 0  
    # customerid is na
# zero-value transaction 
    # quantity > 0 
    # unitprice == 0

normalize_transaction_col = raw_transactions.copy()

conditions = [
    # account adjustment
    normalize_transaction_col['UnitPrice'] < 0,

    # cancellation
    normalize_transaction_col['InvoiceNo'].str.startswith('C', na=False),

    # inventory adjustment
    (normalize_transaction_col['Quantity'] < 0) & 
    (normalize_transaction_col['UnitPrice']  == 0) & 
    (normalize_transaction_col['CustomerID'].isna() == True),

    # zero-value transactions
    (normalize_transaction_col['Quantity'] > 0) & 
    (normalize_transaction_col['UnitPrice']  == 0)


]

conditions_categories = [
    'Account Adjustment',
    'Cancellation',
    'Inventory Adjustment',
    'Zero-Value Transaction'
]

normalize_transaction_col['TransactionType'] = np.select(conditions,conditions_categories, default='Sale')


print(normalize_transaction_col.head())

print(f"The number of rows that are account adjustment: {len(normalize_transaction_col[normalize_transaction_col['TransactionType'] == 'Account Adjustment'])}")
print(f"The number of rows that are cancellation: {len(normalize_transaction_col[normalize_transaction_col['TransactionType'] == 'Cancellation'])}")
print(f"The number of rows that are inventory adjustment: {len(normalize_transaction_col[normalize_transaction_col['TransactionType'] == 'Inventory Adjustment'])}")
print(f"The number of rows that are zero-value transaction: {len(normalize_transaction_col[normalize_transaction_col['TransactionType'] == 'Zero-Value Transaction'])}")
print(f"The number of rows that are sales: {len(normalize_transaction_col[normalize_transaction_col['TransactionType'] == 'Sale'])}")

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

          InvoiceDate  UnitPrice  CustomerID         Country TransactionType
0 2010-12-01 08:26:00       2.55     17850.0  United Kingdom            Sale
1 2010-12-01 08:26:00       3.39     17850.0  United Kingdom            Sale
2 2010-12-01 08:26:00       2.75     17850.0  United Kingdom            Sale
3 2010-12-01 08:26:00       3.39     17850.0  United Kingdom            Sale
4 2010-12-01 08:26:00       3.39     17850.0  United Kingdom            Sale
The number of rows that are account adjustment: 2
The number of rows that are cancellation: 9288
The number of rows that are inventory adjustment: 1336
The number of rows that are zero-value transaction: 1179
The number of rows that are sales: 530104

In [30]:
duplicated_normalize_transaction_col_with_keep = normalize_transaction_col[normalize_transaction_col.duplicated(keep=False)]
print(duplicated_normalize_transaction_col_with_keep.head(),"\n")
print(len(duplicated_normalize_transaction_col_with_keep),"\n")

duplicated_normalize_transaction_col = normalize_transaction_col[normalize_transaction_col.duplicated()]

print(duplicated_normalize_transaction_col.head(),"\n")
print(len(duplicated_normalize_transaction_col))
print(duplicated_normalize_transaction_col['TransactionType'].value_counts())

    InvoiceNo StockCode                       Description  Quantity  \
485    536409     22111      SCOTTIE DOG HOT WATER BOTTLE         1
489    536409     22866     HAND WARMER SCOTTY DOG DESIGN         1
494    536409     21866       UNION JACK FLAG LUGGAGE TAG         1
517    536409     21866       UNION JACK FLAG LUGGAGE TAG         1
521    536409     22900   SET 2 TEA TOWELS I LOVE LONDON          1

            InvoiceDate  UnitPrice  CustomerID         Country TransactionType
485 2010-12-01 11:45:00       4.95     17908.0  United Kingdom            Sale
489 2010-12-01 11:45:00       2.10     17908.0  United Kingdom            Sale
494 2010-12-01 11:45:00       1.25     17908.0  United Kingdom            Sale
517 2010-12-01 11:45:00       1.25     17908.0  United Kingdom            Sale
521 2010-12-01 11:45:00       2.95     17908.0  United Kingdom            Sale

10147

    InvoiceNo StockCode                        Description  Quantity  \
517    536409     21866        UNION JACK FLAG LUGGAGE TAG         1
527    536409     22866      HAND WARMER SCOTTY DOG DESIGN         1
537    536409     22900    SET 2 TEA TOWELS I LOVE LONDON          1
539    536409     22111       SCOTTIE DOG HOT WATER BOTTLE         1
555    536412     22327  ROUND SNACK BOXES SET OF 4 SKULLS         1

            InvoiceDate  UnitPrice  CustomerID         Country TransactionType
517 2010-12-01 11:45:00       1.25     17908.0  United Kingdom            Sale
527 2010-12-01 11:45:00       2.10     17908.0  United Kingdom            Sale
537 2010-12-01 11:45:00       2.95     17908.0  United Kingdom            Sale
539 2010-12-01 11:45:00       4.95     17908.0  United Kingdom            Sale
555 2010-12-01 11:49:00       2.95     17920.0  United Kingdom            Sale

5268
TransactionType
Sale                      5226
Cancellation                37
Zero-Value Transaction       5
Name: count, dtype: int64

In [31]:
duplicate_mask = normalize_transaction_col.duplicated(subset=['InvoiceNo','StockCode','Quantity'], keep = False)
all_duplicates = normalize_transaction_col[duplicate_mask]

intra_invoice_counts = (
    all_duplicates.groupby(['InvoiceNo','StockCode','Quantity']).size().reset_index(name = 'AppearanceCount')
                        )


same_invoice_clusters = intra_invoice_counts[intra_invoice_counts['AppearanceCount'] > 1]

cross_invoice_counts = (
    all_duplicates.groupby(['StockCode', 'Quantity'])['InvoiceNo']
    .nunique()
    .reset_index(name='UniqueInvoiceCount')
)

different_invoice_spans = cross_invoice_counts[cross_invoice_counts['UniqueInvoiceCount'] > 1]



print(f"Total rows involved in duplicates: {len(all_duplicates)}")
print(f"Distinct items repeated WITHIN the same invoice: {len(same_invoice_clusters)}")
print(f"Distinct items repeated ACROSS different invoices: {len(different_invoice_spans)}")

print("\n--- Example of Clustered Duplicates (Same Invoice) ---")
print(same_invoice_clusters.head())

print("\n--- Example of Spanned Duplicates (Different Invoices) ---")
print(different_invoice_spans.head())

Total rows involved in duplicates: 10426
Distinct items repeated WITHIN the same invoice: 4995
Distinct items repeated ACROSS different invoices: 979

--- Example of Clustered Duplicates (Same Invoice) ---
  InvoiceNo StockCode  Quantity  AppearanceCount
0    536409     21866         1                2
1    536409     22111         1                2
2    536409     22866         1                2
3    536409     22900         1                2
4    536412     21448         1                2

--- Example of Spanned Duplicates (Different Invoices) ---
   StockCode  Quantity  UniqueInvoiceCount
4      10135         1                   2
11    15056P         1                   2
18     16225         1                   2
20     16237         1                   2
21     16238         1                   2

In [32]:
print(len(normalize_transaction_col))

print()

541909

In [33]:
normalize_transaction_col.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 9 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   InvoiceNo        541909 non-null  object
 1   StockCode        541909 non-null  object
 2   Description      540455 non-null  object
 3   Quantity         541909 non-null  int64
 4   InvoiceDate      541909 non-null  datetime64[ns]
 5   UnitPrice        541909 non-null  float64
 6   CustomerID       406829 non-null  float64
 7   Country          541909 non-null  object
 8   TransactionType  541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(5)
memory usage: 37.2+ MB

In [34]:
# Checks if the remainder is 0 when divided by 1
is_always_whole = (normalize_transaction_col['CustomerID'].dropna() % 1 == 0).all()
print(f"Are all IDs whole numbers? {is_always_whole}")

Are all IDs whole numbers? True

In [35]:
fact_sale = r"C:\Users\Kaden\retail_sales_etl_pipeline\data\processed\fact_sales.csv"
fact_adjustment = r"C:\Users\Kaden\retail_sales_etl_pipeline\data\processed\fact_adjustments.csv"
fact_cancellations = r"C:\Users\Kaden\retail_sales_etl_pipeline\data\processed\fact_cancellations.csv"
non_sale = r"C:\Users\Kaden\retail_sales_etl_pipeline\data\processed\non_sales.csv"

fact_sale_df = pd.read_csv(fact_sale)
fact_adjustment_df = pd.read_csv(fact_adjustment)
fact_cancellations_df = pd.read_csv(fact_cancellations)
non_sale_df = pd.read_csv(non_sale)

print(f"Total number of rows in fact_sale_df: {len(fact_sale_df)}")



def unique_combination_count(df):
    combination_count = (
        df[
            ['InvoiceNo', 'StockCode','Description','Quantity', 'InvoiceDate', 'UnitPrice']
        ]
        .drop_duplicates()
        .shape[0]
    )
    

    return combination_count

def unique_dupilcates(df):
    duplicates = ( 
        df[['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice']]
        .duplicated(keep=False)
    )
    duplicate_rows = df[duplicates]
    return duplicate_rows

print(f"\nTotal number of the unique combinations for fact_sale {unique_combination_count(fact_sale_df)}")
print(f"\nTotal number of the unique combinations for fact_adjustment {unique_combination_count(fact_adjustment_df)}")
print(f"\nTotal number of the unique combinations for fact_cancellations {unique_combination_count(fact_cancellations_df)}")
print(f"\nTotal number of the unique combinations for non_sale {unique_combination_count(non_sale_df)}")



print(f"\nTotal number of duplicates of the combination for fact_sale: {len(unique_dupilcates(fact_sale_df))}")
print(f"Total number of duplicates of the combination for fact_adjustment: {len(unique_dupilcates(fact_adjustment_df))}")
print(f"Total number of duplicates of the combination for fact_cancellations: {len(unique_dupilcates(fact_cancellations_df))}")
print(f"Total number of duplicates of the combination for non_sale: {len(unique_dupilcates(non_sale_df))}")

Total number of rows in fact_sale_df: 522504

Total number of the unique combinations for fact_sale 522504

Total number of the unique combinations for fact_adjustment 2143

Total number of the unique combinations for fact_cancellations 8684

Total number of the unique combinations for non_sale 3310

Total number of duplicates of the combination for fact_sale: 0
Total number of duplicates of the combination for fact_adjustment: 0
Total number of duplicates of the combination for fact_cancellations: 0
Total number of duplicates of the combination for non_sale: 0

In [36]:
non_num = fact_sale_df[~fact_sale_df['StockCode'].astype(str).str.isnumeric()]
print(non_num['StockCode'].unique())

print(fact_sale_df['StockCode'].isin(['POST','DOT']).sum())

['85123A' '84406B' '84029G' ... '85179a' '90214U' '47591b']
0

In [37]:
remaining_non_numeric = fact_sale_df[pd.to_numeric(fact_sale_df['StockCode'], errors='coerce').isna()]['StockCode'].unique()
print("Remaining non-numeric stock codes in sale_fact:")
print(remaining_non_numeric)

# Filter for codes that don't start with a digit
true_system_codes = [
    code for code in remaining_non_numeric 
    if isinstance(code, str) and not code[0].isdigit()
]

print("Actual system/fee codes that should be removed:")
print(true_system_codes)

Remaining non-numeric stock codes in sale_fact:
['85123A' '84406B' '84029G' ... '85179a' '90214U' '47591b']
Actual system/fee codes that should be removed:
[]

In [38]:
print("--- CANCELLATIONS TABLE CHECK ---")
print(f"Total Rows: {len(fact_cancellations_df)}")
print(f"Unique Transaction Types: {fact_cancellations_df['TransactionType'].unique()}")
print(f"Invoice prefixes (Should all be 'C'): {fact_cancellations_df['InvoiceNo'].astype(str).str[0].unique()}")
print(f"Sample StockCodes included: {fact_cancellations_df['StockCode'].unique()}")

print("\n--- ADJUSTMENTS TABLE CHECK ---")
print(f"Total Rows: {len(fact_adjustment_df)}")
print(f"Unique Transaction Types: {fact_adjustment_df['TransactionType'].unique()}")
print(f"Sample StockCodes included: {fact_adjustment_df['StockCode'].unique()[:10]}")

print("\n--- NON-SALES TABLE CHECK ---")
print(f"Total Rows: {len(non_sale_df)}")
print(f"Unique Transaction Types: {non_sale_df['TransactionType'].unique()}")
print(f"Sample StockCodes included: {non_sale_df['StockCode'].unique()[:10]}")

--- CANCELLATIONS TABLE CHECK ---
Total Rows: 8684
Unique Transaction Types: ['Cancellation']
Invoice prefixes (Should all be 'C'): ['C']
Sample StockCodes included: ['35004C' '22556' '21984' ... '85127' '16219' '23843']

--- ADJUSTMENTS TABLE CHECK ---
Total Rows: 2143
Unique Transaction Types: ['Inventory Adjustment' 'Account Adjustment' 'Financial Adjustment']
Sample StockCodes included: ['21777' '84952C' '22712' '22028' '85067' '21414' '21653' '85126' '21814'
 '21692']

--- NON-SALES TABLE CHECK ---
Total Rows: 3310
Unique Transaction Types: ['Zero-Value Transaction' 'Administrative / Postage']
Sample StockCodes included: ['22139' '21134' '22145' '37509' '85226A' '85044' '20950' '37461' '84670'
 '84952C']

In [39]:
# Check which codes were moved from sales into adjustments
moved_sales_to_adjust = fact_adjustment_df[fact_adjustment_df['TransactionType'] == 'Sale']['StockCode'].unique()
print("StockCodes moved from Sales into Adjustments:")
print(moved_sales_to_adjust)

StockCodes moved from Sales into Adjustments:
[]

In [40]:
print(fact_adjustment_df['Quantity'].unique())

[  -10   -38   -20    -6   -22    -2   -30   -70  -130   -80  -120   -40
    -5   -12   -25   -14   -15   -69    -3  -140  -320   -24   -35   -21
   -43   -19   -11   -18   -44   -50    -9   -77  -223    -4    -1  -150
   -13  -723  -177   -32  -100   -28  -145   -36   -48  -106   -60  -939
   -54  -201   -53   -29 -2600  -990    -8  -290   -45  -310   -61   -41
   -64   -84 -1400  -300   -57   -59   -16   -31   -17  -207   -52  -206
  -217 -1430  -162  -230  -173  -390  -234   -42    -7   -99   -92  -741
  -400  -114   -88   -33  -391   -87  -278  -154 -3000  -675  -600  -210
  -345  -975 -1200 -1121   -27  -541 -1277  -197 -1100   -63 -5368  -259
   -82  -178  -110   -47  -323  -450  -232   -83  -153  -524 -2472  -105
   -34   -46   -75  -690   -39   -66  -180  -194   -26   -23   -62   -37
   -91  -139  -158 -1479   -55  -576  -750   -93 -1092   -65   -68  -620
   -90  -170 -1512   -51   -56   -49  -160  -360 -2376  -786  -590  -168
  -101   -71  -413  -664   -58  -102   -97 -1300  -212  -125  -144   -96
  -116  -108  -304  -272 -1206   -95  -161  -472  -618  -204 -9058 -9600
  -126  -220  -271 -1440  -324   -78  -118 -1681  -179  -124  -251 -3100
  -169 -2834  -109  -530  -227  -346  -188  -240 -1060   -94  -342  -343
  -455     1  -156  -553  -115  -242   -72  -967  -203 -3167  -252  -443
  -432 -1897  -434   -86  -682  -484  -635  -117 -3667  -384  -138  -752
  -250  -147  -121   -67  -131  -209  -231  -129  -458  -275 -2880  -800
  -430  -380   -74  -192  -365  -104  -270   -73  -306  -200  -111  -840
  -184  -103  -335 -1000  -164  -657 -1671 -1158 -2618 -2003  -674 -4830
  -905 -1128 -1560 -1284   -81  -256  -864  -288  -186 -1510  -550  -327
  -152  -313  -398  -280  -504  -696  -408  -149  -224  -428  -267  -175
   -98  -151 -1131  -135  -900  -155  -355  -337 -1050  -338  -235     2
    12    36     4     5    48    18     6    10     3    24    25    17
     7    20    96    41    60    29   183   456   288    72     8   832
    16    30  1200    76  1600    14   800  -720 -1350  -480]